# Generated by Django 2.2.14 on 2020-12-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_remove_alumno_materias'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='alumnos',
            field=models.ManyToManyField(related_name='materias', to='alumnos.Alumno'),
        ),
    ]
