# Generated by Django 2.2.14 on 2020-12-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='alumnos',
        ),
    ]
