# Generated by Django 2.2.14 on 2020-12-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
