# Generated by Django 2.2.14 on 2020-12-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='materias',
        ),
    ]
