# Generated by Django 2.2.14 on 2020-12-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='materias',
        ),
    ]
